# required
main:
  name: "🔒 Secure Manager"
  key: MANAGER
  link: "/manager/"

# optional
settings:
  view:
    theme: minty

# optional
values:

  # optional
  menu:
    - label: "label.users"
      path: "/users"

    - label: "label.credentials"
      path: "/credentials"

    - label: "label.system"
      path: "/system"