# required
main:
  name: "📄 MongoDB Viewer"
  key: "MONGODB-VIEWER"
  link: "/mongodb-viewer/"

# optional
settings:
  view:
    theme: yeti

# optional
values:

  # optional
  menu:
    - label: "label.source"
      path: "/sources"

    - label: "label.rows"
      path: "/rows"

    - label: "label.records"
      path: "/records"